#!/usr/bin/env python3
"""
Integrated Forensic Report Generator
Combines detailed SIEM-Tools style reporting with comprehensive analysis results.
Generates TXT, JSON, CSV, and HTML reports.
"""

import os
import json
import csv
from pathlib import Path
from datetime import datetime
from typing import Dict, List, Any, Optional
from io import StringIO


class IntegratedReportGenerator:
    def __init__(self, output_dir: str):
        self.output_dir = Path(output_dir)
        self.results: Dict[str, Any] = {}
        self.timestamp = datetime.now().isoformat()

    def load_results(self, results: Dict[str, Any]):
        self.results = results

    def generate_all_reports(self) -> Dict[str, str]:
        """Generate all report formats"""
        reports = {
            "txt": self.generate_text_report(),
            "json": self.generate_json_report(),
            "csv": self.generate_csv_report(),
            "html": self.generate_html_report(),
        }
        return reports

    def generate_text_report(self, output_file: Optional[str] = None) -> str:
        """Generate comprehensive text report"""
        metadata = self.results.get("analysis_metadata", {})
        summary = self.results.get("summary", {})
        
        integrated = self.results.get("integrated_analysis", {})
        integrated_summary = integrated.get("summary", {})
        
        data_wipe = self.results.get("data_wipe_analysis", {})
        hidden_volume = self.results.get("hidden_volume_analysis", {})
        
        partitions = self.results.get("partitions", [])

        report = []
        report.append("=" * 100)
        report.append("                    COMPREHENSIVE FORENSIC ANALYSIS REPORT")
        report.append("                    Generated by Angen Gatram Forensic Analyzer")
        report.append("=" * 100)
        report.append("")
        report.append(f"Analysis Date:     {metadata.get('analyzed_at', self.timestamp)}")
        report.append(f"Output Directory:  {metadata.get('output_directory', str(self.output_dir))}")
        report.append(f"Image Path:       {metadata.get('image_path', 'N/A')}")
        report.append("")

        # Partition Information
        report.append("-" * 100)
        report.append("                              PARTITION INFORMATION")
        report.append("-" * 100)
        for p in partitions[:10]:
            report.append(f"  {p.get('slot', 'N/A'):10} | Size: {p.get('size_sectors', 0) * 512 / (1024**3):.2f} GB | FS: {p.get('fs', 'unknown')}")
        report.append("")

        # Integrated Analysis Summary
        report.append("-" * 100)
        report.append("                    TIMESTAMP INTEGRITY ANALYSIS (SI/FN Comparison)")
        report.append("-" * 100)
        report.append(f"  Total Files Analyzed:    {integrated_summary.get('total_files_analyzed', 0)}")
        report.append(f"  Suspicious Files:        {integrated_summary.get('suspicious_files', 0)}")
        report.append(f"  [CRITICAL] Findings:    {integrated_summary.get('critical_count', 0)}")
        report.append(f"  [HIGH] Findings:        {integrated_summary.get('high_count', 0)}")
        report.append(f"  [MEDIUM] Findings:      {integrated_summary.get('medium_count', 0)}")
        report.append(f"  [LOW] Findings:        {integrated_summary.get('low_count', 0)}")
        report.append("")

        # Show critical findings
        critical_findings = integrated.get("critical_findings", [])
        if critical_findings:
            report.append("=" * 100)
            report.append("                         CRITICAL TIMESTAMP ANOMALIES")
            report.append("=" * 100)
            for i, finding in enumerate(critical_findings[:10], 1):
                report.append(f"\n#{i} FILENAME: {finding.get('filename', 'Unknown')}")
                report.append(f"    Record Number:    {finding.get('file_reference', 0)}")
                report.append(f"    Severity:        {finding.get('overall_severity', 'N/A')}")
                report.append(f"    Score:           {finding.get('overall_score', 0)}")
                
                si = finding.get("si_timestamps", {})
                fn = finding.get("fn_timestamps", {})
                if si.get("created") != "None":
                    report.append(f"    SI Created:      {si.get('created')}")
                if fn.get("created") != "None":
                    report.append(f"    FN Created:      {fn.get('created')}")
                
                delta = finding.get("si_fn_created_delta", 0)
                if delta > 0:
                    report.append(f"    SI/FN Delta:     {delta:.1f} seconds ({delta/86400:.2f} days)")
                
                for indicator in finding.get("indicators", [])[:3]:
                    report.append(f"    - {indicator.get('description', '')}")
            report.append("")

        # High findings
        high_findings = integrated.get("high_findings", [])
        if high_findings:
            report.append("=" * 100)
            report.append("                         HIGH SEVERITY ANOMALIES")
            report.append("=" * 100)
            for i, finding in enumerate(high_findings[:10], 1):
                report.append(f"\n#{i} {finding.get('filename', 'Unknown')} | Score: {finding.get('overall_score', 0)}")
                delta = finding.get("si_fn_created_delta", 0)
                if delta > 0:
                    report.append(f"    SI/FN Delta: {delta:.1f}s ({delta/86400:.2f} days)")
            report.append("")

        # Data Wipe Detection
        report.append("-" * 100)
        report.append("                          DATA WIPE DETECTION")
        report.append("-" * 100)
        if data_wipe.get("wipe_detected"):
            report.append("  [!] DATA WIPING DETECTED")
            report.append(f"  Confidence: {data_wipe.get('confidence', 0) * 100:.1f}%")
            report.append(f"  Summary: {data_wipe.get('summary', '')}")
            
            details = data_wipe.get("details", {})
            if details.get("partition_analysis"):
                for part in details["partition_analysis"]:
                    scan = part.get("partition_scan", {})
                    report.append(f"\n  Partition Analysis:")
                    report.append(f"    - High Entropy: {scan.get('high_entropy_percentage', 0):.1f}%")
                    report.append(f"    - Zero-Filled: {scan.get('zero_percentage', 0):.1f}%")
                    report.append(f"    - Method: {scan.get('method', 'unknown')}")
        else:
            report.append("  [+] No data wiping detected")
        report.append("")

        # Hidden Volume Detection
        report.append("-" * 100)
        report.append("                     HIDDEN VOLUME / ENCRYPTED CONTAINER")
        report.append("-" * 100)
        if hidden_volume.get("wipe_detected"):
            report.append("  [!] HIDDEN VOLUME OR ENCRYPTED CONTAINER DETECTED")
            report.append(f"  Summary: {hidden_volume.get('summary', '')}")
            
            for part in hidden_volume.get("partitions", [])[:5]:
                if part.get("hidden_volume_detected"):
                    report.append(f"\n  Partition: {part.get('partition_slot', 'N/A')}")
                    report.append(f"    Confidence: {part.get('confidence', 0) * 100:.1f}%")
                    report.append(f"    Method: {part.get('detection_method', 'unknown')}")
        else:
            report.append("  [+] No hidden volumes or encrypted containers detected")
        report.append("")

        # Recommendations
        report.append("=" * 100)
        report.append("                              RECOMMENDATIONS")
        report.append("=" * 100)
        report.append("")
        
        if integrated_summary.get("critical_count", 0) > 0:
            report.append("[!] IMMEDIATE ACTION REQUIRED")
            report.append("    - Critical timestamp manipulation detected")
            report.append("    - Isolate system for further investigation")
            report.append("    - Check for known timestomping tools")
            report.append("")
        
        if data_wipe.get("wipe_detected"):
            report.append("[!] DATA DESTRUCTION EVIDENCE")
            report.append("    - Evidence of secure deletion or file shredding")
            report.append("    - Investigate data loss prevention tools")
            report.append("")
        
        if hidden_volume.get("wipe_detected"):
            report.append("[!] ENCRYPTED CONTAINER DETECTED")
            report.append("    - Hidden volume or VeraCrypt container found")
            report.append("    - May contain hidden OS or sensitive data")
            report.append("")

        report.append("[+] Review all findings above for complete analysis.")
        report.append("")
        report.append("=" * 100)
        report.append(f"Report generated: {datetime.now().isoformat()}")
        report.append("=" * 100)

        report_text = "\n".join(report)
        
        if output_file:
            with open(output_file, "w") as f:
                f.write(report_text)
        
        return report_text

    def generate_json_report(self, output_file: Optional[str] = None) -> str:
        """Generate JSON report"""
        json_data = json.dumps(self.results, indent=2, default=str)
        
        if output_file:
            with open(output_file, "w") as f:
                f.write(json_data)
        
        return json_data

    def generate_csv_report(self, output_file: Optional[str] = None) -> str:
        """Generate CSV report of all findings"""
        output = StringIO()
        writer = csv.writer(output)
        
        writer.writerow(["Type", "Filename", "Severity", "Score", "Description", "Details", "Delta Seconds"])
        
        # Integrated findings
        integrated = self.results.get("integrated_analysis", {})
        for part_result in integrated.get("partition_results", []):
            for finding in part_result.get("findings", []):
                if finding.get("is_timestomped"):
                    writer.writerow([
                        "Timestomp",
                        finding.get("filename", ""),
                        finding.get("overall_severity", ""),
                        finding.get("overall_score", 0),
                        finding.get("indicators", [{}])[0].get("description", ""),
                        json.dumps(finding.get("evidence", {})),
                        finding.get("si_fn_created_delta", 0),
                    ])
        
        # Data wipe
        data_wipe = self.results.get("data_wipe_analysis", {})
        for indicator in data_wipe.get("indicators", []):
            writer.writerow([
                "Data Wipe",
                indicator.get("file_path", "N/A"),
                indicator.get("severity", ""),
                indicator.get("confidence", 0) * 100,
                indicator.get("description", ""),
                indicator.get("evidence", ""),
                0,
            ])
        
        csv_content = output.getvalue()
        
        if output_file:
            with open(output_file, "w", newline="") as f:
                f.write(csv_content)
        
        return csv_content

    def generate_html_report(self, output_file: Optional[str] = None) -> str:
        """Generate comprehensive HTML report"""
        metadata = self.results.get("analysis_metadata", {})
        summary = self.results.get("summary", {})
        
        integrated = self.results.get("integrated_analysis", {})
        integrated_summary = integrated.get("summary", {})
        
        data_wipe = self.results.get("data_wipe_analysis", {})
        hidden_volume = self.results.get("hidden_volume_analysis", {})
        
        partitions = self.results.get("partitions", [])

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Forensic Analysis Report</title>
    <style>
        body {{ font-family: 'Segoe UI', Tahoma, sans-serif; margin: 0; padding: 20px; background: #1a1a2e; color: #eee; }}
        .container {{ max-width: 1400px; margin: 0 auto; }}
        h1, h2, h3 {{ color: #00d9ff; }}
        h1 {{ text-align: center; border-bottom: 3px solid #00d9ff; padding-bottom: 15px; }}
        .section {{ background: #16213e; padding: 20px; margin: 20px 0; border-radius: 10px; border-left: 4px solid #00d9ff; }}
        .critical {{ border-left-color: #ff4444; }}
        .high {{ border-left-color: #ff8800; }}
        .medium {{ border-left-color: #ffdd00; }}
        .low {{ border-left-color: #00ff00; }}
        .summary-box {{ display: flex; gap: 20px; flex-wrap: wrap; justify-content: center; }}
        .summary-item {{ background: #0f3460; padding: 15px 30px; border-radius: 8px; text-align: center; }}
        .summary-item .number {{ font-size: 2em; font-weight: bold; }}
        .summary-item.critical .number {{ color: #ff4444; }}
        .summary-item.high .number {{ color: #ff8800; }}
        .summary-item.medium .number {{ color: #ffdd00; }}
        .summary-item.low .number {{ color: #00ff00; }}
        .finding {{ background: #0f3460; padding: 15px; margin: 10px 0; border-radius: 5px; }}
        .finding h4 {{ margin: 0 0 10px 0; color: #00d9ff; }}
        .badge {{ display: inline-block; padding: 3px 8px; border-radius: 3px; font-size: 0.8em; font-weight: bold; }}
        .badge-critical {{ background: #ff4444; }}
        .badge-high {{ background: #ff8800; }}
        .badge-medium {{ background: #ffdd00; color: #000; }}
        .badge-low {{ background: #00ff00; color: #000; }}
        table {{ width: 100%; border-collapse: collapse; margin: 10px 0; }}
        th, td {{ padding: 10px; text-align: left; border-bottom: 1px solid #333; }}
        th {{ background: #0f3460; }}
        .timestamp {{ font-family: monospace; color: #aaa; }}
        .alert {{ background: #ff4444; color: white; padding: 15px; border-radius: 5px; margin: 10px 0; }}
        .success {{ background: #00ff00; color: #000; padding: 15px; border-radius: 5px; margin: 10px 0; }}
        .footer {{ text-align: center; margin-top: 30px; color: #666; }}
    </style>
</head>
<body>
    <div class="container">
        <h1>🔍 Comprehensive Forensic Analysis Report</h1>
        
        <div class="section">
            <h2>Analysis Information</h2>
            <p><strong>Date:</strong> {metadata.get('analyzed_at', self.timestamp)}</p>
            <p><strong>Image:</strong> {metadata.get('image_path', 'N/A')}</p>
            <p><strong>Output:</strong> {metadata.get('output_directory', str(self.output_dir))}</p>
        </div>
        
        <div class="section">
            <h2>Partitions Analyzed</h2>
            <table>
                <tr><th>Slot</th><th>Size (GB)</th><th>Filesystem</th><th>Description</th></tr>
"""
        
        for p in partitions[:10]:
            size_gb = p.get('size_sectors', 0) * 512 / (1024**3)
            html += f"""                <tr>
                    <td>{p.get('slot', 'N/A')}</td>
                    <td>{size_gb:.2f}</td>
                    <td>{p.get('fs', 'unknown')}</td>
                    <td>{p.get('description', '')}</td>
                </tr>
"""
        
        html += """            </table>
        </div>
        
        <div class="section">
            <h2>Timestamp Integrity Analysis (SI/FN Comparison)</h2>
            <div class="summary-box">
                <div class="summary-item critical">
                    <div class="number">""" + str(integrated_summary.get('critical_count', 0)) + """</div>
                    <div>Critical</div>
                </div>
                <div class="summary-item high">
                    <div class="number">""" + str(integrated_summary.get('high_count', 0)) + """</div>
                    <div>High</div>
                </div>
                <div class="summary-item medium">
                    <div class="number">""" + str(integrated_summary.get('medium_count', 0)) + """</div>
                    <div>Medium</div>
                </div>
                <div class="summary-item low">
                    <div class="number">""" + str(integrated_summary.get('low_count', 0)) + """</div>
                    <div>Low</div>
                </div>
            </div>
            <p style="text-align:center; margin-top:15px;">
                Total Files: <strong>""" + str(integrated_summary.get('total_files_analyzed', 0)) + """</strong> | 
                Suspicious: <strong>""" + str(integrated_summary.get('suspicious_files', 0)) + """</strong>
            </p>
        </div>
"""
        
        # Critical findings
        critical_findings = integrated.get("critical_findings", [])
        if critical_findings:
            html += """        <div class="section critical">
            <h2>⚠️ Critical Timestamp Anomalies</h2>
"""
            for finding in critical_findings[:10]:
                si = finding.get("si_timestamps", {})
                fn = finding.get("fn_timestamps", {})
                delta = finding.get("si_fn_created_delta", 0)
                
                html += f"""            <div class="finding">
                <h4>{finding.get('filename', 'Unknown')} 
                    <span class="badge badge-critical">{finding.get('overall_severity', '')}</span>
                </h4>
                <p><strong>Score:</strong> {finding.get('overall_score', 0)} | 
                   <strong>SI/FN Delta:</strong> {delta:.1f}s ({delta/86400:.2f} days)</p>
                <p class="timestamp">SI Created: {si.get('created', 'N/A')} | FN Created: {fn.get('created', 'N/A')}</p>
            </div>
"""
            html += "        </div>\n"
        
        # High findings
        high_findings = integrated.get("high_findings", [])
        if high_findings:
            html += """        <div class="section high">
            <h2>⚠️ High Severity Anomalies</h2>
"""
            for finding in high_findings[:15]:
                delta = finding.get("si_fn_created_delta", 0)
                html += f"""            <div class="finding">
                <h4>{finding.get('filename', 'Unknown')}
                    <span class="badge badge-high">HIGH</span>
                </h4>
                <p>Score: {finding.get('overall_score', 0)} | Delta: {delta:.1f}s ({delta/86400:.2f} days)</p>
            </div>
"""
            html += "        </div>\n"
        
        # Data Wipe
        html += """        <div class="section">
            <h2>🗑️ Data Wipe Detection</h2>
"""
        if data_wipe.get("wipe_detected"):
            html += f"""            <div class="alert">
                <strong>⚠️ DATA WIPING DETECTED</strong>
                <p>Confidence: {data_wipe.get('confidence', 0) * 100:.1f}%</p>
                <p>{data_wipe.get('summary', '')}</p>
            </div>
"""
            for indicator in data_wipe.get("indicators", [])[:5]:
                html += f"""            <div class="finding">
                <h4>{indicator.get('type', '')} <span class="badge badge-high">{indicator.get('severity', '')}</span></h4>
                <p>{indicator.get('description', '')}</p>
                <p class="timestamp">{indicator.get('evidence', '')}</p>
            </div>
"""
        else:
            html += """            <div class="success">✓ No data wiping detected</div>
"""
        html += "        </div>\n"
        
        # Hidden Volume
        html += """        <div class="section">
            <h2>🔐 Hidden Volume / Encrypted Container</h2>
"""
        if hidden_volume.get("wipe_detected"):
            html += f"""            <div class="alert">
                <strong>⚠️ ENCRYPTED CONTAINER DETECTED</strong>
                <p>{hidden_volume.get('summary', '')}</p>
            </div>
"""
            for part in hidden_volume.get("partitions", [])[:5]:
                if part.get("hidden_volume_detected"):
                    html += f"""            <div class="finding">
                <h4>Partition: {part.get('partition_slot', '')} 
                    <span class="badge badge-critical">DETECTED</span>
                </h4>
                <p>Confidence: {part.get('confidence', 0) * 100:.1f}% | Method: {part.get('detection_method', '')}</p>
            </div>
"""
        else:
            html += """            <div class="success">✓ No hidden volumes detected</div>
"""
        html += """        </div>
        
        <div class="footer">
            <p>Report generated by Angen Gatram Forensic Analyzer</p>
            <p>""" + datetime.now().isoformat() + """</p>
        </div>
    </div>
</body>
</html>"""
        
        if output_file:
            with open(output_file, "w") as f:
                f.write(html)
        
        return html


def generate_integrated_report(output_dir: str, results: Dict[str, Any]) -> Dict[str, str]:
    """Generate all report formats"""
    generator = IntegratedReportGenerator(output_dir)
    generator.load_results(results)
    
    reports = generator.generate_all_reports()
    
    # Save reports to files
    txt_file = Path(output_dir) / "forensic_report.txt"
    json_file = Path(output_dir) / "forensic_report.json"
    csv_file = Path(output_dir) / "forensic_report.csv"
    html_file = Path(output_dir) / "forensic_report.html"
    
    with open(txt_file, "w") as f:
        f.write(reports["txt"])
    
    with open(json_file, "w") as f:
        f.write(reports["json"])
    
    with open(csv_file, "w", newline="") as f:
        f.write(reports["csv"])
    
    with open(html_file, "w") as f:
        f.write(reports["html"])
    
    return {
        "txt": str(txt_file),
        "json": str(json_file),
        "csv": str(csv_file),
        "html": str(html_file),
    }


if __name__ == "__main__":
    import sys
    
    if len(sys.argv) < 2:
        print("Usage: python integrated_report_generator.py <output_dir>")
        sys.exit(1)
    
    output_dir = sys.argv[1]
    
    results_file = Path(output_dir) / "integrated_forensic_analysis.json"
    if results_file.exists():
        import json
        with open(results_file) as f:
            results = json.load(f)
    else:
        results = {}
    
    reports = generate_integrated_report(output_dir, results)
    
    print("Reports generated:")
    for fmt, path in reports.items():
        print(f"  {fmt}: {path}")
